# yaml-language-server: $schema=https://cloud.dqo.ai/dqo-yaml-schema/TableYaml-schema.json
apiVersion: dqo/v1
kind: table
spec:
  target:
    schema_name: dqo_testing_time_lag
    table_name: crypto_dogecoin
  timestamp_columns:
    event_timestamp_column: timestamp
    ingestion_timestamp_column: inserted_at
    partitioned_checks_timestamp_source: event_timestamp
  checks:
    standard:
      row_count:
        error:
          min_count: 100
        warning: {}
    timeliness:
      days_since_most_recent_event:
        error:
          max_days: 2.0
      data_ingestion_delay:
        error:
          max_days: 2.0
      days_since_most_recent_ingestion:
        error:
          max_days: 2.0
  checkpoints:
    daily:
      standard:
        daily_checkpoint_row_count:
          error:
            min_count: 100
      timeliness:
        daily_checkpoint_days_since_most_recent_event:
          error:
            max_days: 2.0
        daily_checkpoint_data_ingestion_delay:
          error:
            max_days: 2.0
        daily_checkpoint_days_since_most_recent_ingestion:
          error:
            max_days: 2.0
    monthly:
      standard:
        monthly_checkpoint_row_count:
          error:
            min_count: 100
      timeliness:
        monthly_checkpoint_days_since_most_recent_event:
          error:
            max_days: 2.0
        monthly_checkpoint_data_ingestion_delay:
          error:
            max_days: 2.0
        monthly_checkpoint_days_since_most_recent_ingestion:
          error:
            max_days: 2.0
  partitioned_checks:
    daily:
      standard:
        daily_partition_row_count:
          error:
            min_count: 100
      timeliness:
        daily_partition_days_since_most_recent_event:
          error:
            max_days: 2.0
        daily_partition_data_ingestion_delay:
          error:
            max_days: 2.0
        daily_partition_days_since_most_recent_ingestion:
          error:
            max_days: 2.0
    monthly:
      standard:
        monthly_partition_min_row_count:
          error:
            min_count: 100
      timeliness:
        monthly_partition_days_since_most_recent_event:
          error:
            max_days: 2.0
        monthly_partition_data_ingestion_delay:
          error:
            max_days: 2.0
        monthly_partition_days_since_most_recent_ingestion:
          error:
            max_days: 2.0
  schedules_override:
    profiling:
      cron_expression: 15 10 * * *
    daily:
      cron_expression: 0 10 * * *
    monthly:
      cron_expression: 0 10 * * *
  columns:
    hash:
      type_snapshot:
        column_type: STRING
        nullable: false
    size:
      type_snapshot:
        column_type: INT64
        nullable: true
    stripped_size:
      type_snapshot:
        column_type: INT64
        nullable: true
    weight:
      type_snapshot:
        column_type: INT64
        nullable: true
    number:
      type_snapshot:
        column_type: INT64
        nullable: false
    version:
      type_snapshot:
        column_type: INT64
        nullable: true
      checks:
        nulls:
          nulls_count:
            error:
              max_count: 5
          nulls_percent:
            error:
              max_percent: 1.0
      checkpoints:
        daily:
          nulls:
            daily_checkpoint_nulls_count:
              error:
                max_count: 5
            daily_checkpoint_nulls_percent:
              error:
                max_percent: 2.0
        monthly:
          nulls:
            monthly_checkpoint_nulls_count:
              error:
                max_count: 5
            monthly_checkpoint_nulls_percent:
              error:
                max_percent: 2.0
      partitioned_checks:
        daily:
          nulls:
            daily_partition_nulls_count:
              error:
                max_count: 5
            daily_partition_nulls_percent:
              error:
                max_percent: 1.0
        monthly:
          nulls:
            monthly_partition_nulls_count:
              error:
                max_count: 5
            monthly_partition_nulls_percent:
              error:
                max_percent: 1.0
    merkle_root:
      type_snapshot:
        column_type: STRING
        nullable: true
    timestamp:
      type_snapshot:
        column_type: TIMESTAMP
        nullable: false
    timestamp_month:
      type_snapshot:
        column_type: DATE
        nullable: false
    nonce:
      type_snapshot:
        column_type: STRING
        nullable: true
    bits:
      type_snapshot:
        column_type: STRING
        nullable: true
    coinbase_param:
      type_snapshot:
        column_type: STRING
        nullable: true
    transaction_count:
      type_snapshot:
        column_type: INT64
        nullable: true
    inserted_at:
      type_snapshot:
        column_type: TIMESTAMP
        nullable: true
