# yaml-language-server: $schema=https://cloud.dqo.ai/dqo-yaml-schema/TableYaml-schema.json
apiVersion: dqo/v1
kind: table
spec:
  target:
    schema_name: dqo_testing_time_lag
    table_name: crypto_dogecoin
  timestamp_columns:
    event_timestamp_column: timestamp
    ingestion_timestamp_column: inserted_at
    partitioned_checks_timestamp_source: event_timestamp
  checks:
    standard:
      row_count:
        error:
          min_count: 20
        warning:
          min_count: 5
        fatal:
          min_count: 100
  columns:
    hash:
      type_snapshot:
        column_type: STRING
        nullable: false
    size:
      type_snapshot:
        column_type: INT64
        nullable: true
      checks:
        nulls:
          nulls_count:
            error:
              max_count: 50
            warning:
              max_count: 10
            fatal:
              max_count: 100
          nulls_percent: {}
        numeric:
          sample_stddev_in_range:
            error:
              from: -10.0
              to: 10.0
    stripped_size:
      type_snapshot:
        column_type: INT64
        nullable: true
    weight:
      type_snapshot:
        column_type: INT64
        nullable: true
    number:
      type_snapshot:
        column_type: INT64
        nullable: false
    version:
      type_snapshot:
        column_type: INT64
        nullable: true
    merkle_root:
      type_snapshot:
        column_type: STRING
        nullable: true
    timestamp:
      type_snapshot:
        column_type: TIMESTAMP
        nullable: false
    timestamp_month:
      type_snapshot:
        column_type: DATE
        nullable: false
    nonce:
      type_snapshot:
        column_type: STRING
        nullable: true
    bits:
      type_snapshot:
        column_type: STRING
        nullable: true
    coinbase_param:
      type_snapshot:
        column_type: STRING
        nullable: true
      checkpoints:
        daily:
          nulls:
            daily_checkpoint_nulls_count:
              error:
                max_count: 0
        monthly:
          nulls:
            monthly_checkpoint_nulls_count:
              error:
                max_count: 0
    transaction_count:
      type_snapshot:
        column_type: INT64
        nullable: true
    inserted_at:
      type_snapshot:
        column_type: TIMESTAMP
        nullable: true
