# yaml-language-server: $schema=https://cloud.dqo.ai/dqo-yaml-schema/ConnectionYaml-schema.json
apiVersion: dqo/v1
kind: source
spec:
  provider_type: bigquery
  bigquery:
    source_project_id: bigquery-public-data
    authentication_mode: google_application_credentials
    jobs_create_project: create_jobs_in_default_project_from_credentials
  schedules:
    profiling:
      cron_expression: 0 11 * * *
