# yaml-language-server: $schema=https://cloud.dqo.ai/dqo-yaml-schema/TableYaml-schema.json
apiVersion: dqo/v1
kind: table
spec:
  filter: '`timestamp`>="2022-11-20"'
  timestamp_columns:
    event_timestamp_column: timestamp
    ingestion_timestamp_column: timestamp
    partition_by_column: timestamp
  incremental_time_window:
    daily_partitioning_recent_days: 7
    monthly_partitioning_recent_months: 1
  monitoring_checks:
    daily:
      schema:
        daily_column_count:
          warning:
            expected_value: 9
          error:
            expected_value: 7
          fatal:
            expected_value: 5
        daily_column_count_changed:
          warning: {}
          error: {}
          fatal: {}
        daily_column_list_changed:
          warning: {}
          error: {}
          fatal: {}
        daily_column_list_or_order_changed:
          warning: {}
          error: {}
          fatal: {}
        daily_column_types_changed:
          warning: {}
          error: {}
          fatal: {}
  partitioned_checks:
    monthly:
      volume:
        monthly_partition_row_count_change:
          error:
            max_percent: 20.0
  columns:
    hash:
      type_snapshot:
        column_type: STRING
        nullable: false
    size:
      type_snapshot:
        column_type: INT64
        nullable: true
      partitioned_checks:
        daily:
          nulls:
            daily_partition_nulls_count:
              warning:
                max_count: 4
              error:
                max_count: 6
              fatal:
                max_count: 9
            daily_partition_nulls_percent:
              warning:
                max_percent: 1.0
              error:
                max_percent: 2.0
              fatal:
                max_percent: 5.0
        monthly:
          nulls:
            monthly_partition_nulls_count:
              warning:
                max_count: 4
              error:
                max_count: 6
              fatal:
                max_count: 9
            monthly_partition_nulls_percent:
              warning:
                max_percent: 1.0
              error:
                max_percent: 9.0
              fatal:
                max_percent: 5.0
    stripped_size:
      type_snapshot:
        column_type: INT64
        nullable: true
    weight:
      type_snapshot:
        column_type: INT64
        nullable: true
    number:
      type_snapshot:
        column_type: INT64
        nullable: false
      monitoring_checks:
        daily:
          nulls:
            daily_nulls_count:
              warning:
                max_count: 4
              error:
                max_count: 6
              fatal:
                max_count: 9
            daily_nulls_percent:
              warning:
                max_percent: 1.0
              error:
                max_percent: 2.0
              fatal:
                max_percent: 5.0
    version:
      type_snapshot:
        column_type: INT64
        nullable: true
    merkle_root:
      type_snapshot:
        column_type: STRING
        nullable: true
    timestamp:
      type_snapshot:
        column_type: TIMESTAMP
        nullable: false
    timestamp_month:
      type_snapshot:
        column_type: DATE
        nullable: false
    nonce:
      type_snapshot:
        column_type: STRING
        nullable: true
    bits:
      type_snapshot:
        column_type: STRING
        nullable: true
    coinbase_param:
      type_snapshot:
        column_type: STRING
        nullable: true
    transaction_count:
      type_snapshot:
        column_type: INT64
        nullable: true
