# yaml-language-server: $schema=https://cloud.dqo.ai/dqo-yaml-schema/TableYaml-schema.json
apiVersion: dqo/v1
kind: table
spec:
  target:
    schema_name: crypto_dogecoin
    table_name: blocks
  filter: '`timestamp`>="2022-11-20"'
  timestamp_columns:
    event_timestamp_column: timestamp
    partitioned_checks_timestamp_source: event_timestamp
  checkpoints:
    daily:
      standard:
        daily_checkpoint_row_count:
          error:
            min_count: 2
          warning:
            min_count: 1
          fatal:
            min_count: 3
  columns:
    hash:
      type_snapshot:
        column_type: STRING
        nullable: false
    size:
      type_snapshot:
        column_type: INT64
        nullable: true
      checks:
        nulls:
          nulls_count:
            error:
              max_count: 3
            warning:
              max_count: 0
            fatal:
              max_count: 10
          nulls_percent:
            error:
              max_percent: 5.0
            warning:
              max_percent: 1.0
            fatal:
              max_percent: 10.0
      checkpoints:
        daily:
          nulls:
            daily_checkpoint_nulls_count:
              error:
                max_count: 10
              warning:
                max_count: 5
              fatal:
                max_count: 15
            daily_checkpoint_nulls_percent:
              error:
                max_percent: 5.0
              warning:
                max_percent: 2.0
              fatal:
                max_percent: 10.0
    stripped_size:
      type_snapshot:
        column_type: INT64
        nullable: true
    weight:
      type_snapshot:
        column_type: INT64
        nullable: true
    number:
      type_snapshot:
        column_type: INT64
        nullable: false
      checkpoints:
        daily:
          nulls:
            daily_checkpoint_nulls_count:
              error:
                max_count: 6
              warning:
                max_count: 4
              fatal:
                max_count: 9
            daily_checkpoint_nulls_percent:
              error:
                max_percent: 2.0
              warning:
                max_percent: 1.0
              fatal:
                max_percent: 5.0
    version:
      type_snapshot:
        column_type: INT64
        nullable: true
    merkle_root:
      type_snapshot:
        column_type: STRING
        nullable: true
    timestamp:
      type_snapshot:
        column_type: TIMESTAMP
        nullable: false
    timestamp_month:
      type_snapshot:
        column_type: DATE
        nullable: false
    nonce:
      type_snapshot:
        column_type: STRING
        nullable: true
    bits:
      type_snapshot:
        column_type: STRING
        nullable: true
    coinbase_param:
      type_snapshot:
        column_type: STRING
        nullable: true
    transaction_count:
      type_snapshot:
        column_type: INT64
        nullable: true
