# yaml-language-server: $schema=https://cloud.dqo.ai/dqo-yaml-schema/TableYaml-schema.json
apiVersion: dqo/v1
kind: table
spec:
  incremental_time_window:
    daily_partitioning_recent_days: 7
    monthly_partitioning_recent_months: 1
  profiling_checks:
    availability:
      profile_table_availability:
        error:
          max_failures: 5
    schema:
      profile_column_count:
        warning:
          expected_value: 8
        error:
          expected_value: 10
        fatal:
          expected_value: 12
      profile_column_count_changed:
        error: {}
      profile_column_list_changed:
        error: {}
      profile_column_list_or_order_changed:
        error: {}
      profile_column_types_changed:
        error: {}
  monitoring_checks:
    daily:
      volume:
        daily_row_count:
          warning:
            min_count: 18190
          error:
            min_count: 18150
          fatal:
            min_count: 18100
        daily_row_count_change:
          warning:
            max_percent: 10.0
          error:
            max_percent: 20.0
          fatal:
            max_percent: 50.0
        daily_row_count_change_yesterday:
          warning:
            max_percent: 10.0
            exact_day: false
          error:
            max_percent: 20.0
            exact_day: false
          fatal:
            max_percent: 50.0
            exact_day: false
        daily_row_count_change_7_days:
          warning:
            max_percent: 10.0
            exact_day: false
          error:
            max_percent: 20.0
            exact_day: false
          fatal:
            max_percent: 50.0
            exact_day: false
        daily_row_count_change_30_days:
          warning:
            max_percent: 10.0
            exact_day: false
          error:
            max_percent: 20.0
            exact_day: false
          fatal:
            max_percent: 50.0
            exact_day: false
      availability:
        daily_table_availability:
          error:
            max_failures: 5
      schema:
        daily_column_count:
          error:
            expected_value: 9
        daily_column_count_changed:
          warning: {}
          error: {}
          fatal: {}
        daily_column_list_changed:
          warning: {}
          error: {}
          fatal: {}
        daily_column_list_or_order_changed:
          warning: {}
          error: {}
          fatal: {}
        daily_column_types_changed:
          warning: {}
          error: {}
          fatal: {}
    monthly:
      volume:
        monthly_row_count:
          error:
            min_count: 0
        monthly_row_count_change:
          error:
            max_percent: 20.0
      schema:
        monthly_column_count:
          error:
            expected_value: 8
          fatal:
            expected_value: 10
        monthly_column_count_changed:
          error: {}
        monthly_column_list_changed:
          error: {}
        monthly_column_list_or_order_changed:
          error: {}
        monthly_column_types_changed:
          error: {}
  columns:
    edition:
      type_snapshot:
        column_type: INT64
        nullable: true
    report_type:
      type_snapshot:
        column_type: STRING
        nullable: true
    measure_name:
      type_snapshot:
        column_type: STRING
        nullable: true
    state_name:
      type_snapshot:
        column_type: STRING
        nullable: true
    subpopulation:
      type_snapshot:
        column_type: STRING
        nullable: true
    value:
      type_snapshot:
        column_type: FLOAT64
        nullable: true
    lower_ci:
      type_snapshot:
        column_type: FLOAT64
        nullable: true
    upper_ci:
      type_snapshot:
        column_type: FLOAT64
        nullable: true
    source:
      type_snapshot:
        column_type: STRING
        nullable: true
    source_date:
      type_snapshot:
        column_type: STRING
        nullable: true
