# yaml-language-server: $schema=https://cloud.dqo.ai/dqo-yaml-schema/TableYaml-schema.json
apiVersion: dqo/v1
kind: table
spec:
  incremental_time_window:
    daily_partitioning_recent_days: 7
    monthly_partitioning_recent_months: 1
  profiling_checks:
    standard:
      row_count:
        error:
          min_count: 0
  recurring_checks:
    daily:
      standard:
        daily_row_count:
          warning:
            min_count: 18156
          error:
            min_count: 18120
          fatal:
            min_count: 18100
      timeliness:
        daily_days_since_most_recent_event:
          error:
            max_days: 2.0
      availability:
        daily_table_availability:
          error:
            max_failures: 2
  partitioned_checks:
    daily:
      standard:
        daily_partition_row_count:
          error:
            min_count: 10
  columns:
    edition:
      type_snapshot:
        column_type: INT64
        nullable: true
    report_type:
      type_snapshot:
        column_type: STRING
        nullable: true
    measure_name:
      type_snapshot:
        column_type: STRING
        nullable: true
    state_name:
      type_snapshot:
        column_type: STRING
        nullable: true
    subpopulation:
      type_snapshot:
        column_type: STRING
        nullable: true
    value:
      type_snapshot:
        column_type: FLOAT64
        nullable: true
    lower_ci:
      type_snapshot:
        column_type: FLOAT64
        nullable: true
    upper_ci:
      type_snapshot:
        column_type: FLOAT64
        nullable: true
    source:
      type_snapshot:
        column_type: STRING
        nullable: true
    source_date:
      type_snapshot:
        column_type: STRING
        nullable: true
