# yaml-language-server: $schema=https://cloud.dqo.ai/dqo-yaml-schema/TableYaml-schema.json
apiVersion: dqo/v1
kind: table
spec:
  incremental_time_window:
    daily_partitioning_recent_days: 7
    monthly_partitioning_recent_months: 1
  profiling_checks:
    volume:
      row_count:
        error:
          min_count: 249
  recurring_checks:
    daily:
      volume:
        daily_row_count:
          error:
            min_count: 249
  columns:
    country_name:
      type_snapshot:
        column_type: STRING
        nullable: true
      profiling_checks:
        nulls:
          nulls_count:
            error:
              max_count: 0
      recurring_checks:
        daily:
          nulls:
            daily_nulls_count:
              error:
                max_count: 0
    alpha_2_code:
      type_snapshot:
        column_type: STRING
        nullable: true
    alpha_3_code:
      type_snapshot:
        column_type: STRING
        nullable: true
