# yaml-language-server: $schema=https://cloud.dqo.ai/dqo-yaml-schema/TableYaml-schema.json
apiVersion: dqo/v1
kind: table
spec:
  timestamp_columns:
    partition_by_column: block_timestamp
  incremental_time_window:
    daily_partitioning_recent_days: 7
    monthly_partitioning_recent_months: 1
  columns:
    hash:
      type_snapshot:
        column_type: STRING
        nullable: false
    size:
      type_snapshot:
        column_type: INT64
        nullable: true
    virtual_size:
      type_snapshot:
        column_type: INT64
        nullable: true
    version:
      type_snapshot:
        column_type: INT64
        nullable: true
    lock_time:
      type_snapshot:
        column_type: INT64
        nullable: true
    block_hash:
      type_snapshot:
        column_type: STRING
        nullable: false
    block_number:
      type_snapshot:
        column_type: INT64
        nullable: false
    block_timestamp:
      type_snapshot:
        column_type: TIMESTAMP
        nullable: false
    block_timestamp_month:
      type_snapshot:
        column_type: DATE
        nullable: false
    input_count:
      type_snapshot:
        column_type: INT64
        nullable: true
    output_count:
      type_snapshot:
        column_type: INT64
        nullable: true
    input_value:
      type_snapshot:
        column_type: NUMERIC
        nullable: true
    output_value:
      type_snapshot:
        column_type: NUMERIC
        nullable: true
    is_coinbase:
      type_snapshot:
        column_type: BOOL
        nullable: true
    fee:
      type_snapshot:
        column_type: NUMERIC
        nullable: true
    inputs:
      type_snapshot:
        column_type: "ARRAY<STRUCT<index INT64, spent_transaction_hash STRING, spent_output_index\
          \ INT64, script_asm STRING, script_hex STRING, sequence INT64, required_signatures\
          \ INT64, type STRING, addresses ARRAY<STRING>, value NUMERIC>>"
        nullable: false
    outputs:
      type_snapshot:
        column_type: "ARRAY<STRUCT<index INT64, script_asm STRING, script_hex STRING,\
          \ required_signatures INT64, type STRING, addresses ARRAY<STRING>, value\
          \ NUMERIC>>"
        nullable: false
