# yaml-language-server: $schema=https://cloud.dqo.ai/dqo-yaml-schema/TableYaml-schema.json
apiVersion: dqo/v1
kind: table
spec:
  timestamp_columns:
    event_timestamp_column: timestamp
    ingestion_timestamp_column: timestamp
    partition_by_column: timestamp
  incremental_time_window:
    daily_partitioning_recent_days: 7
    monthly_partitioning_recent_months: 1
  columns:
    hash:
      type_snapshot:
        column_type: STRING
        nullable: false
    size:
      type_snapshot:
        column_type: INT64
        nullable: true
    stripped_size:
      type_snapshot:
        column_type: INT64
        nullable: true
    weight:
      type_snapshot:
        column_type: INT64
        nullable: true
    number:
      type_snapshot:
        column_type: INT64
        nullable: false
    version:
      type_snapshot:
        column_type: INT64
        nullable: true
    merkle_root:
      type_snapshot:
        column_type: STRING
        nullable: true
    timestamp:
      type_snapshot:
        column_type: TIMESTAMP
        nullable: false
    timestamp_month:
      type_snapshot:
        column_type: DATE
        nullable: false
    nonce:
      type_snapshot:
        column_type: STRING
        nullable: true
    bits:
      type_snapshot:
        column_type: STRING
        nullable: true
    coinbase_param:
      type_snapshot:
        column_type: STRING
        nullable: true
    transaction_count:
      type_snapshot:
        column_type: INT64
        nullable: true
