# yaml-language-server: $schema=https://cloud.dqo.ai/dqo-yaml-schema/TableYaml-schema.json
apiVersion: dqo/v1
kind: table
spec:
  target:
    schema_name: thelook_ecommerce
    table_name: users
  timestamp_columns:
    partitioned_checks_timestamp_source: event_timestamp
  columns:
    id:
      type_snapshot:
        column_type: INT64
        nullable: true
      checks:
        numeric:
          negative_count:
            error:
              max_count: 10
        strings:
          string_null_placeholder_count:
            disabled: true
            error:
              max_count: 10
            fatal:
              max_count: 50
          string_null_placeholder_percent:
            disabled: true
            error:
              max_percent: 2.0
    first_name:
      type_snapshot:
        column_type: STRING
        nullable: true
    last_name:
      type_snapshot:
        column_type: STRING
        nullable: true
    email:
      type_snapshot:
        column_type: STRING
        nullable: true
    age:
      type_snapshot:
        column_type: INT64
        nullable: true
    gender:
      type_snapshot:
        column_type: STRING
        nullable: true
    state:
      type_snapshot:
        column_type: STRING
        nullable: true
    street_address:
      type_snapshot:
        column_type: STRING
        nullable: true
    postal_code:
      type_snapshot:
        column_type: STRING
        nullable: true
    city:
      type_snapshot:
        column_type: STRING
        nullable: true
    country:
      type_snapshot:
        column_type: STRING
        nullable: true
    latitude:
      type_snapshot:
        column_type: FLOAT64
        nullable: true
    longitude:
      type_snapshot:
        column_type: FLOAT64
        nullable: true
    traffic_source:
      type_snapshot:
        column_type: STRING
        nullable: true
      checks:
        nulls:
          nulls_count:
            error:
              max_count: 20
            warning:
              max_count: 10
            fatal:
              max_count: 40
        numeric:
          negative_count:
            disabled: true
            error:
              max_count: 10
            warning:
              max_count: 5
            fatal:
              max_count: 20
        strings:
          string_max_length:
            error:
              max_value: 2.0
            warning:
              max_value: 1.0
            fatal:
              max_value: 5.0
          string_min_length:
            error:
              min_value: 2.0
            warning:
              min_value: 1.0
            fatal:
              min_value: 5.0
    created_at:
      type_snapshot:
        column_type: TIMESTAMP
        nullable: true
