# yaml-language-server: $schema=https://cloud.dqo.ai/dqo-yaml-schema/TableYaml-schema.json
apiVersion: dqo/v1
kind: table
spec:
  incremental_time_window:
    daily_partitioning_recent_days: 7
    monthly_partitioning_recent_months: 1
  columns:
    order_id:
      type_snapshot:
        column_type: INT64
        nullable: true
    user_id:
      type_snapshot:
        column_type: INT64
        nullable: true
    status:
      type_snapshot:
        column_type: STRING
        nullable: true
    gender:
      type_snapshot:
        column_type: STRING
        nullable: true
    created_at:
      type_snapshot:
        column_type: TIMESTAMP
        nullable: true
    returned_at:
      type_snapshot:
        column_type: TIMESTAMP
        nullable: true
    shipped_at:
      type_snapshot:
        column_type: TIMESTAMP
        nullable: true
    delivered_at:
      type_snapshot:
        column_type: TIMESTAMP
        nullable: true
    num_of_item:
      type_snapshot:
        column_type: INT64
        nullable: true
