# yaml-language-server: $schema=https://cloud.dqo.ai/dqo-yaml-schema/TableYaml-schema.json
apiVersion: dqo/v1
kind: table
spec:
  incremental_time_window:
    daily_partitioning_recent_days: 7
    monthly_partitioning_recent_months: 1
  columns:
    id:
      type_snapshot:
        column_type: INT64
        nullable: true
    user_id:
      type_snapshot:
        column_type: INT64
        nullable: true
    sequence_number:
      type_snapshot:
        column_type: INT64
        nullable: true
    session_id:
      type_snapshot:
        column_type: STRING
        nullable: true
    created_at:
      type_snapshot:
        column_type: TIMESTAMP
        nullable: true
    ip_address:
      type_snapshot:
        column_type: STRING
        nullable: true
    city:
      type_snapshot:
        column_type: STRING
        nullable: true
    state:
      type_snapshot:
        column_type: STRING
        nullable: true
    postal_code:
      type_snapshot:
        column_type: STRING
        nullable: true
    browser:
      type_snapshot:
        column_type: STRING
        nullable: true
    traffic_source:
      type_snapshot:
        column_type: STRING
        nullable: true
    uri:
      type_snapshot:
        column_type: STRING
        nullable: true
    event_type:
      type_snapshot:
        column_type: STRING
        nullable: true
