# yaml-language-server: $schema=https://cloud.dqo.ai/dqo-yaml-schema/TableYaml-schema.json
apiVersion: dqo/v1
kind: table
spec:
  target:
    schema_name: thelook_ecommerce
    table_name: order_items
  timestamp_columns:
    event_timestamp_column: created_at
    partitioned_checks_timestamp_source: event_timestamp
  schedule_override:
    cron_expression: 15 9 * * *
  columns:
    id:
      type_snapshot:
        column_type: INT64
        nullable: true
    order_id:
      type_snapshot:
        column_type: INT64
        nullable: true
    user_id:
      type_snapshot:
        column_type: INT64
        nullable: true
    product_id:
      type_snapshot:
        column_type: INT64
        nullable: true
    inventory_item_id:
      type_snapshot:
        column_type: INT64
        nullable: true
    status:
      type_snapshot:
        column_type: STRING
        nullable: true
    created_at:
      type_snapshot:
        column_type: TIMESTAMP
        nullable: true
    shipped_at:
      type_snapshot:
        column_type: TIMESTAMP
        nullable: true
    delivered_at:
      type_snapshot:
        column_type: TIMESTAMP
        nullable: true
    returned_at:
      type_snapshot:
        column_type: TIMESTAMP
        nullable: true
    sale_price:
      type_snapshot:
        column_type: FLOAT64
        nullable: true
