# yaml-language-server: $schema=https://cloud.dqo.ai/dqo-yaml-schema/TableYaml-schema.json
apiVersion: dqo/v1
kind: table
spec:
  target:
    schema_name: kaggle_student_performance
    table_name: maths
  timestamp_columns:
    partitioned_checks_timestamp_source: event_timestamp
  columns:
    school:
      type_snapshot:
        column_type: STRING
        nullable: true
    sex:
      type_snapshot:
        column_type: STRING
        nullable: true
    age:
      type_snapshot:
        column_type: INT64
        nullable: true
    address:
      type_snapshot:
        column_type: STRING
        nullable: true
    famsize:
      type_snapshot:
        column_type: STRING
        nullable: true
    Pstatus:
      type_snapshot:
        column_type: STRING
        nullable: true
    Medu:
      type_snapshot:
        column_type: INT64
        nullable: true
    Fedu:
      type_snapshot:
        column_type: INT64
        nullable: true
    Mjob:
      type_snapshot:
        column_type: STRING
        nullable: true
    Fjob:
      type_snapshot:
        column_type: STRING
        nullable: true
    reason:
      type_snapshot:
        column_type: STRING
        nullable: true
    guardian:
      type_snapshot:
        column_type: STRING
        nullable: true
    traveltime:
      type_snapshot:
        column_type: INT64
        nullable: true
    studytime:
      type_snapshot:
        column_type: INT64
        nullable: true
    failures:
      type_snapshot:
        column_type: INT64
        nullable: true
    schoolsup:
      type_snapshot:
        column_type: BOOL
        nullable: true
    famsup:
      type_snapshot:
        column_type: BOOL
        nullable: true
    paid:
      type_snapshot:
        column_type: BOOL
        nullable: true
      checks:
        numeric:
          min_numbers_in_set_percent:
            parameters:
              values:
              - 1
            error:
              min_percent: 25.0
            warning:
              min_percent: 23.0
            fatal:
              min_percent: 12.0
        strings:
          min_string_boolean_placeholder_percent:
            error:
              min_percent: 100.0
            warning:
              min_percent: 99.0
            fatal:
              min_percent: 95.0
      checkpoints:
        daily:
          bool:
            daily_checkpoint_min_true_percent:
              error:
                min_percent: 80.0
              warning:
                min_percent: 85.0
              fatal:
                min_percent: 70.0
    activities:
      type_snapshot:
        column_type: BOOL
        nullable: true
    nursery:
      type_snapshot:
        column_type: BOOL
        nullable: true
    higher:
      type_snapshot:
        column_type: BOOL
        nullable: true
    internet:
      type_snapshot:
        column_type: BOOL
        nullable: true
    romantic:
      type_snapshot:
        column_type: BOOL
        nullable: true
    famrel:
      type_snapshot:
        column_type: INT64
        nullable: true
    freetime:
      type_snapshot:
        column_type: INT64
        nullable: true
    goout:
      type_snapshot:
        column_type: INT64
        nullable: true
    Dalc:
      type_snapshot:
        column_type: INT64
        nullable: true
    Walc:
      type_snapshot:
        column_type: INT64
        nullable: true
    health:
      type_snapshot:
        column_type: INT64
        nullable: true
    absences:
      type_snapshot:
        column_type: INT64
        nullable: true
    G1:
      type_snapshot:
        column_type: INT64
        nullable: true
    G2:
      type_snapshot:
        column_type: INT64
        nullable: true
    G3:
      type_snapshot:
        column_type: INT64
        nullable: true
