# yaml-language-server: $schema=https://cloud.dqops.com/dqo-yaml-schema/TableYaml-schema.json
apiVersion: dqo/v1
kind: table
spec:
  incremental_time_window:
    daily_partitioning_recent_days: 7
    monthly_partitioning_recent_months: 1
  default_grouping_name: qwert
  groupings:
    qwert:
      level_1:
        source: column_value
        column: qweerr
  partitioned_checks:
    daily:
      volume:
        daily_partition_row_count:
          fatal:
            min_count: 90000000000000
  columns: {}
