# yaml-language-server: $schema=https://cloud.dqo.ai/dqo-yaml-schema/ConnectionYaml-schema.json
apiVersion: dqo/v1
kind: source
spec:
  provider_type: bigquery
  bigquery:
    source_project_id: dqo-ai-testing
    authentication_mode: google_application_credentials
  snowflake: {}
  postgresql:
    port: 5432
    ssl: false
  schedules:
    profiling:
      cron_expression: 0 11 * * *
    daily:
      cron_expression: 0 11 * * *
    monthly:
      cron_expression: 0 11 * * *
