# yaml-language-server: $schema=https://cloud.dqops.com/dqo-yaml-schema/TableYaml-schema.json
apiVersion: dqo/v1
kind: table
spec:
  timestamp_columns:
    event_timestamp_column: timestamp
    ingestion_timestamp_column: inserted_at
    partition_by_column: timestamp
  incremental_time_window:
    daily_partitioning_recent_days: 7
    monthly_partitioning_recent_months: 1
  default_grouping_name: group
  groupings:
    group:
      level_1:
        source: column_value
        column: bits
  partitioned_checks:
    daily:
      volume:
        daily_partition_row_count:
          warning:
            min_count: 900000000000000
  columns:
    hash:
      type_snapshot:
        column_type: STRING
        nullable: false
    size:
      type_snapshot:
        column_type: INT64
        nullable: true
    stripped_size:
      type_snapshot:
        column_type: INT64
        nullable: true
    weight:
      type_snapshot:
        column_type: INT64
        nullable: true
    number:
      type_snapshot:
        column_type: INT64
        nullable: false
    version:
      type_snapshot:
        column_type: INT64
        nullable: true
    merkle_root:
      type_snapshot:
        column_type: STRING
        nullable: true
    timestamp:
      type_snapshot:
        column_type: TIMESTAMP
        nullable: false
    timestamp_month:
      type_snapshot:
        column_type: DATE
        nullable: false
    nonce:
      type_snapshot:
        column_type: STRING
        nullable: true
    bits:
      type_snapshot:
        column_type: STRING
        nullable: true
      partitioned_checks:
        daily:
          nulls:
            daily_partition_nulls_count:
              error:
                max_count: 10
          strings:
            daily_partition_string_max_length:
              error:
                max_value: 3.0
            daily_partition_string_min_length:
              error:
                min_value: 7.0
          uniqueness:
            daily_partition_distinct_count:
              error:
                min_count: 1
    coinbase_param:
      type_snapshot:
        column_type: STRING
        nullable: true
    transaction_count:
      type_snapshot:
        column_type: INT64
        nullable: true
    inserted_at:
      type_snapshot:
        column_type: TIMESTAMP
        nullable: false
