# yaml-language-server: $schema=https://cloud.dqo.ai/dqo-yaml-schema/TableYaml-schema.json
apiVersion: dqo/v1
kind: table
spec:
  timestamp_columns:
    event_timestamp_column: timestamp
    ingestion_timestamp_column: inserted_at
    partition_by_column: timestamp
  incremental_time_window:
    daily_partitioning_recent_days: 7
    monthly_partitioning_recent_months: 1
  profiling_checks:
    schema:
      column_count:
        error:
          expected_value: 10
  partitioned_checks:
    daily:
      volume:
        daily_partition_row_count:
          error:
            min_count: 0
      timeliness:
        daily_partition_data_freshness:
          error:
            max_days: 2.0
  columns:
    hash:
      type_snapshot:
        column_type: STRING
        nullable: false
    size:
      type_snapshot:
        column_type: INT64
        nullable: true
    stripped_size:
      type_snapshot:
        column_type: INT64
        nullable: true
    weight:
      type_snapshot:
        column_type: INT64
        nullable: true
    number:
      type_snapshot:
        column_type: INT64
        nullable: false
      partitioned_checks:
        daily:
          nulls:
            daily_partition_nulls_count:
              error:
                max_count: 0
    version:
      type_snapshot:
        column_type: INT64
        nullable: true
    merkle_root:
      type_snapshot:
        column_type: STRING
        nullable: true
    timestamp:
      type_snapshot:
        column_type: TIMESTAMP
        nullable: false
    timestamp_month:
      type_snapshot:
        column_type: DATE
        nullable: false
    nonce:
      type_snapshot:
        column_type: STRING
        nullable: true
    bits:
      type_snapshot:
        column_type: STRING
        nullable: true
      profiling_checks:
        nulls:
          nulls_count:
            error:
              max_count: 10
          nulls_percent:
            error:
              max_percent: 2.0
        numeric:
          negative_count:
            error:
              max_count: 10
          negative_percent:
            error:
              max_percent: 2.0
          non_negative_count:
            error:
              max_count: 10
          non_negative_percent:
            error:
              max_percent: 99.0
          expected_numbers_in_use_count:
            error:
              max_missing: 1
        strings:
          string_max_length:
            error:
              max_value: 60.0
          string_min_length:
            error:
              min_value: 4.0
          string_mean_length:
            error:
              from: 4.0
              to: 40.0
          string_empty_count:
            error:
              max_count: 10
          string_empty_percent:
            error:
              max_percent: 2.0
        uniqueness:
          distinct_count:
            error:
              min_count: 0
          distinct_percent:
            error:
              min_percent: 99.0
          duplicate_count:
            error:
              max_count: 0
        datetime:
          date_values_in_future_percent:
            error:
              max_percent: 2.0
        pii:
          valid_usa_phone_percent:
            error:
              min_percent: 99.0
          contains_usa_phone_percent:
            error:
              max_percent: 2.0
          valid_usa_zipcode_percent:
            error:
              min_percent: 99.0
          contains_usa_zipcode_percent:
            error:
              max_percent: 2.0
          valid_email_percent:
            error:
              min_percent: 99.0
          contains_email_percent:
            error:
              min_percent: 99.0
        bool:
          true_percent:
            error:
              min_percent: 99.0
          false_percent:
            error:
              min_percent: 99.0
    coinbase_param:
      type_snapshot:
        column_type: STRING
        nullable: true
    transaction_count:
      type_snapshot:
        column_type: INT64
        nullable: true
    inserted_at:
      type_snapshot:
        column_type: TIMESTAMP
        nullable: false
