# yaml-language-server: $schema=https://cloud.dqops.com/dqo-yaml-schema/TableYaml-schema.json
apiVersion: dqo/v1
kind: table
spec:
  incremental_time_window:
    daily_partitioning_recent_days: 7
    monthly_partitioning_recent_months: 1
  columns:
    Restaurant_ID:
      type_snapshot:
        column_type: INT64
        nullable: true
    Name:
      type_snapshot:
        column_type: STRING
        nullable: true
    City:
      type_snapshot:
        column_type: STRING
        nullable: true
    State:
      type_snapshot:
        column_type: STRING
        nullable: true
    Country:
      type_snapshot:
        column_type: STRING
        nullable: true
    Zip_Code:
      type_snapshot:
        column_type: INT64
        nullable: true
    Latitude:
      type_snapshot:
        column_type: FLOAT64
        nullable: true
    Longitude:
      type_snapshot:
        column_type: FLOAT64
        nullable: true
    Alcohol_Service:
      type_snapshot:
        column_type: STRING
        nullable: true
    Smoking_Allowed:
      type_snapshot:
        column_type: STRING
        nullable: true
    Price:
      type_snapshot:
        column_type: STRING
        nullable: true
    Franchise:
      type_snapshot:
        column_type: BOOL
        nullable: true
    Area:
      type_snapshot:
        column_type: STRING
        nullable: true
    Parking:
      type_snapshot:
        column_type: STRING
        nullable: true
