# yaml-language-server: $schema=https://cloud.dqops.com/dqo-yaml-schema/TableYaml-schema.json
apiVersion: dqo/v1
kind: table
spec:
  incremental_time_window:
    daily_partitioning_recent_days: 7
    monthly_partitioning_recent_months: 1
  columns:
    Consumer_ID:
      type_snapshot:
        column_type: STRING
        nullable: true
    Restaurant_ID:
      type_snapshot:
        column_type: INT64
        nullable: true
    Overall_Rating:
      type_snapshot:
        column_type: INT64
        nullable: true
    Food_Rating:
      type_snapshot:
        column_type: INT64
        nullable: true
    Service_Rating:
      type_snapshot:
        column_type: INT64
        nullable: true
