# yaml-language-server: $schema=https://cloud.dqo.ai/dqo-yaml-schema/TableYaml-schema.json
apiVersion: dqo/v1
kind: table
spec:
  incremental_time_window:
    daily_partitioning_recent_days: 7
    monthly_partitioning_recent_months: 1
  columns:
    Consumer_ID:
      type_snapshot:
        column_type: STRING
        nullable: true
      profiling_checks:
        uniqueness:
          profile_distinct_percent:
            warning:
              min_percent: 100.0
            error:
              min_percent: 99.0
            fatal:
              min_percent: 95.0
    City:
      type_snapshot:
        column_type: STRING
        nullable: true
    State:
      type_snapshot:
        column_type: STRING
        nullable: true
    Country:
      type_snapshot:
        column_type: STRING
        nullable: true
    Latitude:
      type_snapshot:
        column_type: FLOAT64
        nullable: true
    Longitude:
      type_snapshot:
        column_type: FLOAT64
        nullable: true
    Smoker:
      type_snapshot:
        column_type: BOOL
        nullable: true
    Drink_Level:
      type_snapshot:
        column_type: STRING
        nullable: true
    Transportation_Method:
      type_snapshot:
        column_type: STRING
        nullable: true
      profiling_checks:
        nulls:
          profile_nulls_count:
            error:
              max_count: 5
            fatal:
              max_count: 10
          profile_nulls_percent:
            error:
              max_percent: 5.0
            fatal:
              max_percent: 10.0
        strings:
          profile_string_max_length:
            error:
              max_value: 7.0
          profile_string_min_length:
            error:
              min_value: 3.0
      monitoring_checks:
        daily:
          nulls:
            daily_nulls_count:
              error:
                max_count: 5
              fatal:
                max_count: 10
            daily_nulls_percent:
              error:
                max_percent: 5.0
              fatal:
                max_percent: 10.0
    Marital_Status:
      type_snapshot:
        column_type: STRING
        nullable: true
    Children:
      type_snapshot:
        column_type: STRING
        nullable: true
    Age:
      type_snapshot:
        column_type: INT64
        nullable: true
      profiling_checks:
        nulls:
          profile_nulls_count:
            warning:
              max_count: 0
            error:
              max_count: 10
            fatal:
              max_count: 15
        numeric:
          profile_non_negative_count:
            error:
              max_count: 10
        anomaly:
          profile_mean_change:
            error:
              max_percent: 20.0
      monitoring_checks:
        daily:
          nulls:
            daily_nulls_count:
              error:
                max_count: 0
        monthly:
          nulls:
            monthly_nulls_count:
              error:
                max_count: 0
    Occupation:
      type_snapshot:
        column_type: STRING
        nullable: true
    Budget:
      type_snapshot:
        column_type: STRING
        nullable: true
