# yaml-language-server: $schema=https://cloud.dqo.ai/dqo-yaml-schema/TableYaml-schema.json
apiVersion: dqo/v1
kind: table
spec:
  incremental_time_window:
    daily_partitioning_recent_days: 7
    monthly_partitioning_recent_months: 1
  data_streams:
    default:
      level_1:
        source: tag
        tag: asd
  recurring_checks:
    daily:
      volume:
        daily_row_count:
          error:
            min_count: 0
  columns:
    id:
      type_snapshot:
        column_type: INT64
        nullable: true
    datetime:
      type_snapshot:
        column_type: TIMESTAMP
        nullable: true
    team1:
      type_snapshot:
        column_type: STRING
        nullable: true
    team2:
      type_snapshot:
        column_type: STRING
        nullable: true
    team1_code:
      type_snapshot:
        column_type: STRING
        nullable: true
    team2_code:
      type_snapshot:
        column_type: STRING
        nullable: true
    round:
      type_snapshot:
        column_type: STRING
        nullable: true
    score1:
      type_snapshot:
        column_type: INT64
        nullable: true
    score2:
      type_snapshot:
        column_type: INT64
        nullable: true
    adj_score1:
      type_snapshot:
        column_type: FLOAT64
        nullable: true
    adj_score2:
      type_snapshot:
        column_type: FLOAT64
        nullable: true
    chances1:
      type_snapshot:
        column_type: FLOAT64
        nullable: true
    chances2:
      type_snapshot:
        column_type: FLOAT64
        nullable: true
    moves1:
      type_snapshot:
        column_type: FLOAT64
        nullable: true
    moves2:
      type_snapshot:
        column_type: FLOAT64
        nullable: true
    group:
      type_snapshot:
        column_type: STRING
        nullable: true
    matchday:
      type_snapshot:
        column_type: FLOAT64
        nullable: true
      recurring_checks:
        daily:
          numeric:
            daily_numbers_in_set_count:
              parameters:
                values:
                - 1
                - 2
                - 3
                - 4
                - 5
                - 6
              error:
                min_count: 200
            daily_values_in_range_numeric_percent:
              parameters:
                min_value: 1.0
                max_value: 5.0
              error:
                min_percent: 33.0
