# yaml-language-server: $schema=https://cloud.dqo.ai/dqo-yaml-schema/TableYaml-schema.json
apiVersion: dqo/v1
kind: table
spec:
  target:
    schema_name: kaggle_covidlive
    table_name: covid_live
  timestamp_columns:
    partitioned_checks_timestamp_source: event_timestamp
  schedules_override:
    profiling:
      cron_expression: 15 10 * * *
    daily:
      cron_expression: 15 10 * * *
    monthly:
      cron_expression: 15 10 * * *
  columns:
    Country:
      type_snapshot:
        column_type: INT64
        nullable: true
    _Other:
      type_snapshot:
        column_type: STRING
        nullable: true
    TotalCases:
      type_snapshot:
        column_type: INT64
        nullable: true
      checkpoints:
        daily:
          numeric:
            daily_checkpoint_numbers_in_set_count:
              parameters:
                values:
                - 20
              error:
                min_count: 2
    TotalDeaths:
      type_snapshot:
        column_type: INT64
        nullable: true
    NewDeaths:
      type_snapshot:
        column_type: INT64
        nullable: true
    TotalRecovered:
      type_snapshot:
        column_type: INT64
        nullable: true
    ActiveCases:
      type_snapshot:
        column_type: STRING
        nullable: true
      checkpoints:
        daily:
          nulls:
            daily_checkpoint_nulls_percent:
              error:
                max_percent: 10.0
              fatal:
                max_percent: 25.0
    Serious:
      type_snapshot:
        column_type: STRING
        nullable: true
      checkpoints:
        daily:
          strings:
            daily_checkpoint_string_boolean_placeholder_percent:
              error:
                min_percent: 5.0
              fatal:
                min_percent: 10.0
    Critical:
      type_snapshot:
        column_type: STRING
        nullable: true
    Tot_Cases_1M_pop:
      type_snapshot:
        column_type: STRING
        nullable: true
    Deaths_1M_pop:
      type_snapshot:
        column_type: INT64
        nullable: true
    TotalTests:
      type_snapshot:
        column_type: INT64
        nullable: true
    Tests_1M_pop:
      type_snapshot:
        column_type: INT64
        nullable: true
    Population:
      type_snapshot:
        column_type: INT64
        nullable: true
    int64_field_14:
      type_snapshot:
        column_type: INT64
        nullable: true
    int64_field_15:
      type_snapshot:
        column_type: INT64
        nullable: true
    int64_field_16:
      type_snapshot:
        column_type: INT64
        nullable: true
    int64_field_17:
      type_snapshot:
        column_type: INT64
        nullable: true
    int64_field_18:
      type_snapshot:
        column_type: INT64
        nullable: true
    int64_field_19:
      type_snapshot:
        column_type: INT64
        nullable: true
    int64_field_20:
      type_snapshot:
        column_type: INT64
        nullable: true
    int64_field_21:
      type_snapshot:
        column_type: INT64
        nullable: true
    int64_field_22:
      type_snapshot:
        column_type: INT64
        nullable: true
    int64_field_23:
      type_snapshot:
        column_type: INT64
        nullable: true
    int64_field_24:
      type_snapshot:
        column_type: INT64
        nullable: true
    int64_field_25:
      type_snapshot:
        column_type: INT64
        nullable: true
    int64_field_26:
      type_snapshot:
        column_type: INT64
        nullable: true
    int64_field_27:
      type_snapshot:
        column_type: INT64
        nullable: true
    int64_field_28:
      type_snapshot:
        column_type: INT64
        nullable: true
    int64_field_29:
      type_snapshot:
        column_type: INT64
        nullable: true
    int64_field_30:
      type_snapshot:
        column_type: INT64
        nullable: true
  comments:
  - date: 2022-12-06T11:58:14.937+00:00
    comment_by: user
    comment: "https://www.kaggle.com/datasets/whenamancodes/covid-19-coronavirus-pandemic-dataset;\
      \ Author: AMAN CHAUHAN"
