# yaml-language-server: $schema=https://cloud.dqo.ai/dqo-yaml-schema/TableYaml-schema.json
apiVersion: dqo/v1
kind: table
spec:
  incremental_time_window:
    daily_partitioning_recent_days: 7
    monthly_partitioning_recent_months: 1
  profiling_checks:
    schema:
      column_count:
        error:
          expected_value: 8
  columns:
    Country:
      type_snapshot:
        column_type: INT64
        nullable: true
    _Other:
      type_snapshot:
        column_type: STRING
        nullable: true
    TotalCases:
      type_snapshot:
        column_type: INT64
        nullable: true
    TotalDeaths:
      type_snapshot:
        column_type: INT64
        nullable: true
    NewDeaths:
      type_snapshot:
        column_type: INT64
        nullable: true
    TotalRecovered:
      type_snapshot:
        column_type: INT64
        nullable: true
    ActiveCases:
      type_snapshot:
        column_type: STRING
        nullable: true
      recurring_checks:
        daily:
          nulls:
            daily_nulls_percent:
              error:
                max_percent: 10.0
              fatal:
                max_percent: 25.0
    Serious:
      type_snapshot:
        column_type: STRING
        nullable: true
      recurring_checks:
        daily:
          strings:
            daily_string_boolean_placeholder_percent:
              error:
                min_percent: 5.0
              fatal:
                min_percent: 10.0
    Critical:
      type_snapshot:
        column_type: STRING
        nullable: true
    Tot_Cases_1M_pop:
      type_snapshot:
        column_type: STRING
        nullable: true
    Deaths_1M_pop:
      type_snapshot:
        column_type: INT64
        nullable: true
    TotalTests:
      type_snapshot:
        column_type: INT64
        nullable: true
    Tests_1M_pop:
      type_snapshot:
        column_type: INT64
        nullable: true
    Population:
      type_snapshot:
        column_type: INT64
        nullable: true
    int64_field_14:
      type_snapshot:
        column_type: INT64
        nullable: true
    int64_field_15:
      type_snapshot:
        column_type: INT64
        nullable: true
    int64_field_16:
      type_snapshot:
        column_type: INT64
        nullable: true
    int64_field_17:
      type_snapshot:
        column_type: INT64
        nullable: true
    int64_field_18:
      type_snapshot:
        column_type: INT64
        nullable: true
    int64_field_19:
      type_snapshot:
        column_type: INT64
        nullable: true
    int64_field_20:
      type_snapshot:
        column_type: INT64
        nullable: true
    int64_field_21:
      type_snapshot:
        column_type: INT64
        nullable: true
    int64_field_22:
      type_snapshot:
        column_type: INT64
        nullable: true
    int64_field_23:
      type_snapshot:
        column_type: INT64
        nullable: true
    int64_field_24:
      type_snapshot:
        column_type: INT64
        nullable: true
    int64_field_25:
      type_snapshot:
        column_type: INT64
        nullable: true
    int64_field_26:
      type_snapshot:
        column_type: INT64
        nullable: true
    int64_field_27:
      type_snapshot:
        column_type: INT64
        nullable: true
    int64_field_28:
      type_snapshot:
        column_type: INT64
        nullable: true
    int64_field_29:
      type_snapshot:
        column_type: INT64
        nullable: true
    int64_field_30:
      type_snapshot:
        column_type: INT64
        nullable: true
  comments:
  - date: 2022-12-06T11:58:14.937+00:00
    comment_by: user
    comment: "https://www.kaggle.com/datasets/whenamancodes/covid-19-coronavirus-pandemic-dataset;\
      \ Author: AMAN CHAUHAN"
