# yaml-language-server: $schema=https://cloud.dqo.ai/dqo-yaml-schema/TableYaml-schema.json
apiVersion: dqo/v1
kind: table
spec:
  timestamp_columns:
    event_timestamp_column: date1
    ingestion_timestamp_column: date2
    partition_by_column: date1
  incremental_time_window:
    daily_partitioning_recent_days: 7
    monthly_partitioning_recent_months: 1
  partitioned_checks:
    daily:
      timeliness:
        daily_partition_reload_lag:
          error:
            max_days: 2.0
  columns:
    id:
      type_snapshot:
        column_type: INT64
        nullable: true
    date1:
      type_snapshot:
        column_type: DATETIME
        nullable: true
      partitioned_checks:
        daily:
          nulls:
            daily_partition_nulls_count:
              error:
                max_count: 10
    date2:
      type_snapshot:
        column_type: DATETIME
        nullable: true
    date3:
      type_snapshot:
        column_type: STRING
        nullable: true
    date4:
      type_snapshot:
        column_type: DATETIME
        nullable: true
