# yaml-language-server: $schema=https://cloud.dqo.ai/dqo-yaml-schema/TableYaml-schema.json
apiVersion: dqo/v1
kind: table
spec:
  target:
    schema_name: dqo_ai_test_data
    table_name: nulls_and_uniqueness_6973502192108666536
  timestamp_columns:
    event_timestamp_column: date
    ingestion_timestamp_column: date
    partitioned_checks_timestamp_source: event_timestamp
  incremental_time_window:
    daily_partitioning_recent_days: 7
    monthly_partitioning_recent_months: 1
  columns:
    id:
      type_snapshot:
        column_type: INT64
        nullable: true
    nulls:
      type_snapshot:
        column_type: STRING
        nullable: true
    nulls_ok:
      type_snapshot:
        column_type: INT64
        nullable: true
    unique_count:
      type_snapshot:
        column_type: STRING
        nullable: true
    negative:
      type_snapshot:
        column_type: INT64
        nullable: true
      checks:
        numeric:
          population_stddev_in_range:
            error:
              from: 30.0
              to: 40.0
          sample_variance_in_range:
            error:
              from: 1.0
              to: 150000.0
    usa_phone:
      type_snapshot:
        column_type: STRING
        nullable: true
    usa_phone_ok:
      type_snapshot:
        column_type: INT64
        nullable: true
    usa_zipcode:
      type_snapshot:
        column_type: STRING
        nullable: true
    usa_zipcode_ok:
      type_snapshot:
        column_type: INT64
        nullable: true
    valid_country_code:
      type_snapshot:
        column_type: STRING
        nullable: true
    valid_country_code_ok:
      type_snapshot:
        column_type: INT64
        nullable: true
    valid_currency_code:
      type_snapshot:
        column_type: STRING
        nullable: true
    valid_currency_code_ok:
      type_snapshot:
        column_type: INT64
        nullable: true
    date:
      type_snapshot:
        column_type: DATE
        nullable: true
