# yaml-language-server: $schema=https://cloud.dqo.ai/dqo-yaml-schema/TableYaml-schema.json
apiVersion: dqo/v1
kind: table
spec:
  target:
    schema_name: dqo_ai_test_data
    table_name: string_test_data_7339515149066388344
  timestamp_columns:
    partitioned_checks_timestamp_source: event_timestamp
  incremental_time_window:
    daily_partitioning_recent_days: 7
    monthly_partitioning_recent_months: 1
  columns:
    id:
      type_snapshot:
        column_type: INT64
        nullable: true
    email:
      type_snapshot:
        column_type: STRING
        nullable: true
    email_ok:
      type_snapshot:
        column_type: INT64
        nullable: true
    surrounded_by_whitespace:
      type_snapshot:
        column_type: STRING
        nullable: true
    surrounded_by_whitespace_ok:
      type_snapshot:
        column_type: INT64
        nullable: true
    null_placeholder:
      type_snapshot:
        column_type: STRING
        nullable: true
    null_placeholder_ok:
      type_snapshot:
        column_type: INT64
        nullable: true
    boolean_placeholder:
      type_snapshot:
        column_type: STRING
        nullable: true
    boolean_placeholder_ok:
      type_snapshot:
        column_type: INT64
        nullable: true
    empty_percent:
      type_snapshot:
        column_type: STRING
        nullable: true
    empty_percent_ok:
      type_snapshot:
        column_type: INT64
        nullable: true
    range_numeric:
      type_snapshot:
        column_type: FLOAT64
        nullable: true
    range_integers:
      type_snapshot:
        column_type: INT64
        nullable: true
    date:
      type_snapshot:
        column_type: DATE
        nullable: true
    boolean_type_placeholder:
      type_snapshot:
        column_type: BOOL
        nullable: true
