# yaml-language-server: $schema=https://cloud.dqo.ai/dqo-yaml-schema/TableYaml-schema.json
apiVersion: dqo/v1
kind: table
spec:
  target:
    schema_name: dqo_ai_test_data
    table_name: test_data_values_in_set_7722004775138516608
  timestamp_columns:
    partitioned_checks_timestamp_source: event_timestamp
  columns:
    id:
      type_snapshot:
        column_type: INT64
        nullable: true
    length_int:
      type_snapshot:
        column_type: INT64
        nullable: true
    length_string:
      type_snapshot:
        column_type: STRING
        nullable: true
    mix_string_int:
      type_snapshot:
        column_type: STRING
        nullable: true
    strings_with_numbers:
      type_snapshot:
        column_type: STRING
        nullable: true
    mix_with_missing_data:
      type_snapshot:
        column_type: STRING
        nullable: true
    empty_column:
      type_snapshot:
        column_type: STRING
        nullable: true
