# yaml-language-server: $schema=https://cloud.dqops.com/dqo-yaml-schema/TableYaml-schema.json
apiVersion: dqo/v1
kind: table
spec:
  timestamp_columns:
    partition_by_column: date_col
  incremental_time_window:
    daily_partitioning_recent_days: 7
    monthly_partitioning_recent_months: 1
  columns:
    datetime_col:
      type_snapshot:
        column_type: DATETIME
        nullable: true
    date_col:
      type_snapshot:
        column_type: DATE
        nullable: true
