# yaml-language-server: $schema=https://cloud.dqo.ai/dqo-yaml-schema/TableYaml-schema.json
apiVersion: dqo/v1
kind: table
spec:
  target:
    schema_name: dqo_ai_test_data
    table_name: uuid_test_3020850803489016729
  timestamp_columns:
    partitioned_checks_timestamp_source: event_timestamp
  columns:
    UUID:
      type_snapshot:
        column_type: STRING
        nullable: true
    RESULT:
      type_snapshot:
        column_type: INT64
        nullable: true
    DATE:
      type_snapshot:
        column_type: DATE
        nullable: true
