# yaml-language-server: $schema=https://cloud.dqo.ai/dqo-yaml-schema/TableYaml-schema.json
apiVersion: dqo/v1
kind: table
spec:
  timestamp_columns:
    partition_by_column: date
  incremental_time_window:
    daily_partitioning_recent_days: 7
    monthly_partitioning_recent_months: 1
  columns:
    valid_string_100:
      type_snapshot:
        column_type: STRING
        nullable: true
    valid_string_70:
      type_snapshot:
        column_type: STRING
        nullable: true
    date:
      type_snapshot:
        column_type: DATE
        nullable: true
