# yaml-language-server: $schema=https://cloud.dqops.com/dqo-yaml-schema/TableYaml-schema.json
apiVersion: dqo/v1
kind: table
spec:
  timestamp_columns:
    partition_by_column: date
  incremental_time_window:
    daily_partitioning_recent_days: 7
    monthly_partitioning_recent_months: 1
  columns:
    id:
      type_snapshot:
        column_type: INT64
        nullable: true
    length_int:
      type_snapshot:
        column_type: INT64
        nullable: true
    length_string:
      type_snapshot:
        column_type: STRING
        nullable: true
    mix_string_int:
      type_snapshot:
        column_type: STRING
        nullable: true
    strings_with_numbers:
      type_snapshot:
        column_type: STRING
        nullable: true
    mix_of_values:
      type_snapshot:
        column_type: STRING
        nullable: true
    correct:
      type_snapshot:
        column_type: INT64
        nullable: true
    date:
      type_snapshot:
        column_type: DATE
        nullable: true
