# yaml-language-server: $schema=https://cloud.dqo.ai/dqo-yaml-schema/TableYaml-schema.json
apiVersion: dqo/v1
kind: table
spec:
  timestamp_columns: {}
  incremental_time_window:
    daily_partitioning_recent_days: 7
    monthly_partitioning_recent_months: 1
  columns:
    id:
      type_snapshot:
        column_type: INT64
        nullable: true
    length_int:
      type_snapshot:
        column_type: INT64
        nullable: true
    length_string:
      type_snapshot:
        column_type: STRING
        nullable: true
    mix_string_int:
      type_snapshot:
        column_type: STRING
        nullable: true
    strings_with_numbers:
      type_snapshot:
        column_type: STRING
        nullable: true
    mix_with_missing_data:
      type_snapshot:
        column_type: STRING
        nullable: true
    empty_column:
      type_snapshot:
        column_type: STRING
        nullable: true
