# yaml-language-server: $schema=https://cloud.dqops.com/dqo-yaml-schema/TableYaml-schema.json
apiVersion: dqo/v1
kind: table
spec:
  timestamp_columns:
    partition_by_column: date1
  incremental_time_window:
    daily_partitioning_recent_days: 7
    monthly_partitioning_recent_months: 1
  columns:
    id:
      type_snapshot:
        column_type: INT64
        nullable: true
    date1:
      type_snapshot:
        column_type: DATETIME
        nullable: true
    date2:
      type_snapshot:
        column_type: DATETIME
        nullable: true
    date3:
      type_snapshot:
        column_type: STRING
        nullable: true
    date4:
      type_snapshot:
        column_type: DATETIME
        nullable: true
