# yaml-language-server: $schema=https://cloud.dqo.ai/dqo-yaml-schema/TableYaml-schema.json
apiVersion: dqo/v1
kind: table
spec:
  target:
    schema_name: dqo_ai_test_data
    table_name: nulls_and_uniqueness_3303781671231823558
  timestamp_columns:
    event_timestamp_column: date
    ingestion_timestamp_column: date
    partitioned_checks_timestamp_source: event_timestamp
  incremental_time_window:
    daily_partitioning_recent_days: 7
    monthly_partitioning_recent_months: 1
  checks:
    standard:
      row_count: {}
    timeliness:
      days_since_most_recent_event:
        warning:
          max_days: 100.0
  columns:
    id:
      type_snapshot:
        column_type: INT64
        nullable: true
    nulls:
      type_snapshot:
        column_type: STRING
        nullable: true
      checks:
        numeric:
          sample_stddev_in_range:
            error:
              from: -10.0
              to: 10.0
    nulls_ok:
      type_snapshot:
        column_type: INT64
        nullable: true
      checks:
        numeric:
          sample_stddev_in_range:
            error:
              from: -1.0
              to: 10.0
    unique_count:
      type_snapshot:
        column_type: STRING
        nullable: true
    negative:
      type_snapshot:
        column_type: INT64
        nullable: true
      checkpoints:
        daily:
          numeric:
            daily_checkpoint_min_in_range:
              error:
                from: -100.0
                to: 100.0
            daily_checkpoint_mean_in_range:
              error:
                from: 100.0
                to: 200.0
            daily_checkpoint_population_stddev_in_range:
              error:
                from: 100.0
                to: 120.0
      partitioned_checks:
        daily:
          numeric:
            daily_partition_value_above_max_value_percent:
              error:
                min_percent: 2.0
            daily_partition_min_in_range:
              error:
                from: -100.0
                to: 100.0
            daily_partition_mean_in_range:
              error:
                from: 20.0
                to: 40.0
            daily_partition_population_stddev_in_range:
              error:
                from: -10.0
                to: 10.0
        monthly:
          numeric:
            monthly_partition_population_stddev_in_range:
              error:
                from: -10.0
                to: 10.0
    usa_phone:
      type_snapshot:
        column_type: STRING
        nullable: true
    usa_phone_ok:
      type_snapshot:
        column_type: INT64
        nullable: true
    usa_zipcode:
      type_snapshot:
        column_type: STRING
        nullable: true
    usa_zipcode_ok:
      type_snapshot:
        column_type: INT64
        nullable: true
    valid_country_code:
      type_snapshot:
        column_type: STRING
        nullable: true
    valid_country_code_ok:
      type_snapshot:
        column_type: INT64
        nullable: true
    valid_currency_code:
      type_snapshot:
        column_type: STRING
        nullable: true
    valid_currency_code_ok:
      type_snapshot:
        column_type: INT64
        nullable: true
    date:
      type_snapshot:
        column_type: DATE
        nullable: true
