# yaml-language-server: $schema=https://cloud.dqo.ai/dqo-yaml-schema/TableYaml-schema.json
apiVersion: dqo/v1
kind: table
spec:
  incremental_time_window:
    daily_partitioning_recent_days: 7
    monthly_partitioning_recent_months: 1
  columns:
    BrandName:
      type_snapshot:
        column_type: STRING
        nullable: true
    Type:
      type_snapshot:
        column_type: STRING
        nullable: true
      recurring_checks:
        daily:
          nulls:
            daily_nulls_count:
              error:
                max_count: 1
          strings:
            daily_string_surrounded_by_whitespace_count:
              error:
                max_count: 0
    Size:
      type_snapshot:
        column_type: FLOAT64
        nullable: true
      recurring_checks:
        daily:
          numeric:
            daily_values_in_range_numeric_percent:
              parameters:
                min_value: 30.0
                max_value: 61.0
              error:
                min_percent: 99.0
    BrandSize:
      type_snapshot:
        column_type: STRING
        nullable: true
    Chest:
      type_snapshot:
        column_type: FLOAT64
        nullable: true
    FrontLength:
      type_snapshot:
        column_type: FLOAT64
        nullable: true
    AcrossShoulder:
      type_snapshot:
        column_type: FLOAT64
        nullable: true
  comments:
  - date: 2022-12-06T12:37:19.864+00:00
    comment_by: user
    comment: "https://www.kaggle.com/datasets/saikumartamminana/shirt-size-recommendation;\
      \ Author:  SAIKUMAR TAMMINANA"
