# yaml-language-server: $schema=https://cloud.dqo.ai/dqo-yaml-schema/TableYaml-schema.json
apiVersion: dqo/v1
kind: table
spec:
  target:
    schema_name: dqo_testing_time_lag
    table_name: crypto_dogecoin
  timestamp_columns:
    partitioned_checks_timestamp_source: event_timestamp
  columns:
    hash:
      type_snapshot:
        column_type: STRING
        nullable: false
    size:
      type_snapshot:
        column_type: INT64
        nullable: true
    stripped_size:
      type_snapshot:
        column_type: INT64
        nullable: true
    weight:
      type_snapshot:
        column_type: INT64
        nullable: true
    number:
      type_snapshot:
        column_type: INT64
        nullable: false
    version:
      type_snapshot:
        column_type: INT64
        nullable: true
    merkle_root:
      type_snapshot:
        column_type: STRING
        nullable: true
    timestamp:
      type_snapshot:
        column_type: TIMESTAMP
        nullable: false
    timestamp_month:
      type_snapshot:
        column_type: DATE
        nullable: false
    nonce:
      type_snapshot:
        column_type: STRING
        nullable: true
    bits:
      type_snapshot:
        column_type: STRING
        nullable: true
    coinbase_param:
      type_snapshot:
        column_type: STRING
        nullable: true
    transaction_count:
      type_snapshot:
        column_type: INT64
        nullable: true
    inserted_at:
      type_snapshot:
        column_type: TIMESTAMP
        nullable: true
