# yaml-language-server: $schema=https://cloud.dqo.ai/dqo-yaml-schema/TableYaml-schema.json
apiVersion: dqo/v1
kind: table
spec:
  target:
    schema_name: maven_restaurant_ratings
    table_name: ratings
  timestamp_columns:
    partitioned_checks_timestamp_source: event_timestamp
  columns:
    Consumer_ID:
      type_snapshot:
        column_type: STRING
        nullable: true
    Restaurant_ID:
      type_snapshot:
        column_type: INT64
        nullable: true
    Overall_Rating:
      type_snapshot:
        column_type: INT64
        nullable: true
    Food_Rating:
      type_snapshot:
        column_type: INT64
        nullable: true
    Service_Rating:
      type_snapshot:
        column_type: INT64
        nullable: true
